[package]
name = "evaluator"
version = "0.5.0"
authors = ["wjzz <wjedynak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
